name: Run k6 Tests with Web Dashboard and Logs

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  k6-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install k6 using Snap
        run: |
          sudo snap install k6

      - name: Create output directory
        run: |
          mkdir -p output

      - name: Run smoke test and capture logs
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          K6_WEB_DASHBOARD: true
        run: |
          k6 run tests/smokeTest.js > output/smokeTestLog.txt

      - name: Run soak test and capture logs
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          K6_WEB_DASHBOARD: true
        run: |
          k6 run tests/soakTest.js > output/soakTestLog.txt

      - name: Run spike test and capture logs
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          K6_WEB_DASHBOARD: true
        run: |
          k6 run tests/spikeTest.js > output/spikeTestLog.txt

      - name: Run stress test and capture logs
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          K6_WEB_DASHBOARD: true
        run: |
          k6 run tests/stressTest.js > output/stressTestLog.txt

      - name: Upload logs and test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: k6-logs-and-results
          path: output/
