name: Run k6 Tests with InfluxDB in Azure

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  k6-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-type: [smoke, soak, spike, stress]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set permissions for tests and output directories
        run: |
          chmod -R 777 tests
          mkdir -p output/${{ matrix.test-type }}
          chmod -R 777 output

      - name: Run ${{ matrix.test-type }} test with InfluxDB and Web Dashboard
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          K6_WEB_DASHBOARD: true
          K6_INFLUXDB_URL: 20.220.170.186:8086
          K6_INFLUXDB_BUCKET: ${{ secrets.K6_INFLUXDB_BUCKET }}
          K6_INFLUXDB_ORG: ""
          K6_INFLUXDB_TOKEN: ""
          K6_INFLUXDB_USER: ${{ secrets.K6_INFLUXDB_USER }}
          K6_INFLUXDB_PASSWORD: ${{ secrets.K6_INFLUXDB_PASSWORD }}
        run: |
          docker run --rm -v ${{ github.workspace }}:/tests -w /tests grafana/k6 \
          run --out influxdb=$K6_INFLUXDB_URL/${{ secrets.K6_INFLUXDB_BUCKET }} \
          --out json=output/${{ matrix.test-type }}/result.json \
          $(find tests -name "${{ matrix.test-type }}Test.js")

      - name: Upload ${{ matrix.test-type }} test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: k6-${{ matrix.test-type }}-test-results
          path: output/${{ matrix.test-type }}/