name: Run k6 Tests with Web Dashboard

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  k6-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install k6 using Snap
        run: |
          sudo snap install k6

      - name: Run smoke test with Web Dashboard
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          K6_WEB_DASHBOARD: true
        run: |
          k6 run --out json=output/smokeTestResult.json tests/smokeTest.js

      - name: Run soak test with Web Dashboard
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          K6_WEB_DASHBOARD: true
        run: |
          k6 run --out json=output/soakTestResult.json tests/soakTest.js

      - name: Run spike test with Web Dashboard
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          K6_WEB_DASHBOARD: true
        run: |
          k6 run --out json=output/spikeTestResult.json tests/spikeTest.js

      - name: Run stress test with Web Dashboard
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          K6_WEB_DASHBOARD: true
        run: |
          k6 run --out json=output/stressTestResult.json tests/stressTest.js

      - name: Upload test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: k6-test-results
          path: output/
