name: test performance

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  k6-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        test-type: [smoke, soak, spike, stress]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Crear el directorio de salida para los resultados
      - name: Create output directory
        run: mkdir -p output/${{ matrix.test-type }}

      # Ejecutar la prueba K6 dentro de un contenedor Docker
      - name: Run ${{ matrix.test-type }} test with Web Dashboard using Docker
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
          K6_WEB_DASHBOARD: true
        run: |
          docker run --rm -v ${{ github.workspace }}:/src -w /src loadimpact/k6 \
          run --out json=output/${{ matrix.test-type }}/result.json tests/${{ matrix.test-type }}Test.js

      # Subir los resultados de las pruebas como artefactos
      - name: Upload ${{ matrix.test-type }} test results as artifact
        uses: actions/upload-artifact@v3
        with:
          name: k6-${{ matrix.test-type }}-test-results
          path: output/${{ matrix.test-type }}/
